---
title: "Calendars in R with calendR"
author: "Alex"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M:%S')`"
output: html_document
---

Load packages

```{r, message = FALSE}
library(calendR)
```

```{r}
calendR()
# The default is year = format(Sys.Date(), "%Y")
```

```{r}
calendR(year = 2023)
```

```{r}
calendR(month = 2L)
# month = NULL print all months
```

```{r}
calendR(start_date = "2022-02-12", end_date = "2022-05-28")
```

```{r}
calendR(month = 2L, start = "M")
# Valid options: start = c("S", "M")
```

```{r}
calendR(month = 2L, start = "M", 
        title = "An amazing month!", title.size = 30, title.col = "orange")
# Defaults: title.size = 20, title.col = "gray30"
```

```{r}
calendR(month = 2L, start = "M", 
        # title = "An amazing month!",
        subtitle = "full of joy and excitement", 
        subtitle.size = 12, subtitle.col = "brown")
# Defaults: subtitle.size = 10, subtitle.col = "gray30"
```

```{r}
calendR(month = 2L, start = "M", 
        text = "Valentine's \nday", text.pos = 14, 
        text.size = 4, text.col = "red")
# Defaults: text.size = 4, text.col = "gray30"
```

```{r}
calendR(month = 2L, start = "M", 
        text = "Training", text.pos = c(1, 2, 9, 22, 25), 
        text.size = 4.5, text.col = "blue")
```

```{r}
calendR(month = 2L, start = "M",
        special.days = "weekend", special.col = "lightblue")
# Default: special.col = "gray90"
```

```{r}
special_days_022022 <- sample(1:28, size = 10)
calendR(month = 2L, start = "M",
        special.days = special_days_022022, special.col = "lightblue")
```

```{r}
calendR(month = 2L, start = "M",
        special.days = 1:28, special.col = "lightblue",
        gradient = TRUE, low.col = "white")
# Defaults: gradient = FALSE, low.col = "white"
```

```{r}
special_days_022022 <- sample(1:28, size = 10)
calendR(month = 2L, start = "M",
        special.days = special_days_022022, special.col = "yellow",
        text = "Special \ndays!", text.pos = special_days_022022, 
        text.size = 4.5, text.col = "red")
```

```{r}
calendR(month = 2L, start = "M",
        lunar = TRUE, lunar.col = "gray60", lunar.size = 7)
# Defaults: lunar = FALSE, lunar.col = "gray60", lunar.size = 7
```

```{r}
calendR(month = 2L, start = "M",
        day.size = 4.5, days.col = "green4")
# Defaults: day.size = 3, days.col = "gray30"
```

```{r}
calendR(month = 2L, start = "M",
        weeknames = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"), 
        weeknames.col = "orange", weeknames.size = 8)
# Defaults: weeknames.col = "gray30", weeknames.size = 4.5
```

```{r}
calendR(month = 2L, start = "M",
        weeknames = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"), 
        weeknames.col = "orange", weeknames.size = 8,
        font.family = "mono", font.style = "bold")
# Defaults: font.family = "sans", font.style = "plain"
# font.style = c(plain", "bold", "italic", "bold.italic")
```

```{r}
calendR(start = "M",
        months.size = 10, months.col = "blue", months.pos = 0.5)
# Defaults: months.size = 10, months.col = "gray30", months.pos = 0.5
```

```{r}
calendR(start = "M",
        months.size = 10, months.col = "blue", months.pos = 1,
        mbg.col = "orange")
# Default: mbg.col = "white"
```

```{r}
calendR(month = 2L, start = "M",
        col = "red", lwd = 0.8, lty = 3)
# Defaults: col = "gray30", lwd = 0.5, lty = 1
```

```{r}
calendR(start = "M", orientation = "portrait")
# orientation = c("portrait", "landscape"), default is "landscape"
```

```{r}
calendR(month = 2L, start = "M",
        margin = 1)
# Default: margin = 1
```

```{r}
calendR(month = 2L, start = "M",
        bg.col = "lightblue")
# Default: bg.col = "white"
```
 
```{r}
calendR(month = 2L, start = "M",
        bg.img = "img/cal_img-02.png")
```

```{r}
event_df <- data.frame(
  id = 1:4,
  lbl = c("Trip", "Holidays", "Birthday", "Christmas"),
  col = c("pink", "lightblue", "lightgreen", "lightsalmon")
)
event_df
```

```{r}
year2disp <- 2022
last_day <- as.Date(paste0(year2disp, "-12-31"))
first_day <- as.Date(paste0(year2disp, "-01-01"))
ndays <- as.numeric(difftime(last_day, first_day)) + 1
date_to_int <- function(x) { as.numeric(difftime(as.Date(x), first_day)) + 1 }
```

```{r}
events <- rep(NA, ndays)

event_dates_1 <- paste0(year2disp, "-", "02-", 13:19)
events[date_to_int(event_dates_1)] <- event_df$lbl[1]

event_dates_2 <- paste0(year2disp, "-", "08-", 1:31)
events[date_to_int(event_dates_2)] <- event_df$lbl[2]

event_dates_3 <- paste0(year2disp, "-", "11-", 13)
events[date_to_int(event_dates_3)] <- event_df$lbl[3]

event_dates_4 <- paste0(year2disp, "-", "12-", 25)
events[date_to_int(event_dates_4)] <- event_df$lbl[4]
```

```{r}
calendR(year = year2disp,
        special.days = events,
        special.col = event_df$col,
        legend.pos = "bottom")
# Default: legend.pos = "none", legend.title = ""
# legend.pos = c("none", "top", "bottom", "left", "right")
```

```{r}
event_df <- data.frame(
  id = 1:4,
  lbl = c("Weekend", "Running", "Hiking", "Basketball"),
  col = c("grey", "pink", "lightblue", "lightgreen")
)
event_df
```

```{r}
year2disp <- 2022
month2disp <- 2L
last_day <- as.Date(paste0(year2disp, "-", month2disp, "-", 28))
first_day <- as.Date(paste0(year2disp, "-", month2disp, "-", 1))
ndays <- as.numeric(difftime(last_day, first_day)) + 1
date_to_int <- function(x) { as.numeric(difftime(as.Date(x), first_day)) + 1 }
```

```{r}
events <- rep(NA, ndays)
dates <- seq(from = first_day,to = last_day, by = "1 day")
events <- ifelse(format(dates, "%w") %in% c(6, 0), "Weekend", NA)

event_dates_2 <- as.Date(paste0(year2disp, "-", month2disp, "-", c(2, 3, 10, 11)))
events[date_to_int(event_dates_2)] <- event_df$lbl[2]

event_dates_3 <- as.Date(paste0(year2disp, "-", month2disp, "-", c(18, 19)))
events[date_to_int(event_dates_3)] <- event_df$lbl[3]

event_dates_4 <- as.Date(paste0(year2disp, "-", month2disp, "-", c(2)))
events[date_to_int(event_dates_4)] <- event_df$lbl[4]
```

```{r}
calendR(year = year2disp, month = month2disp, start = "M",
        special.days = events,
        special.col = event_df$col,
        legend.pos = "bottom")
```

```{r}
calendR(year = 2022, start = "M",
        pdf = TRUE,
        doc_name = "My_calendar")
# Defaults: pdf = FALSE, doc_name = "", papersize = "A4"
```
